-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, P.PRICE * SALE AS SALES
FROM PRODUCT P,(SELECT PRODUCT_ID,SUM(SALES_AMOUNT) AS SALE FROM OFFLINE_SALE GROUP BY PRODUCT_ID) O
WHERE P.PRODUCT_ID = O.PRODUCT_ID 
ORDER BY 2 DESC,1