SELECT TO_CHAR(n.SALES_DATE,'YYYY-MM-DD') AS SALES_DATE,
n.PRODUCT_ID,
n.USER_ID,
n.SALES_AMOUNT
FROM ONLINE_SALE n
WHERE EXTRACT(YEAR FROM n.SALES_DATE) = 2022
AND EXTRACT(MONTH FROM n.SALES_DATE) = 3
UNION
SELECT TO_CHAR(f.SALES_DATE,'YYYY-MM-DD') AS SALES_DATE,
f.PRODUCT_ID,
NULL,
f.SALES_AMOUNT
FROM OFFLINE_SALE f
WHERE EXTRACT(YEAR FROM f.SALES_DATE) = 2022
AND EXTRACT(MONTH FROM f.SALES_DATE) = 3
ORDER BY 1,2,3