SELECT A.HISTORY_ID,A.CAR_ID,
TO_CHAR(A.START_DATE,'YYYY-MM-DD'),
TO_CHAR(A.END_DATE,'YYYY-MM-DD'),
CASE WHEN (A.END_DATE - A.START_DATE) +1 >= 30
            THEN '장기 대여'
            ELSE '단기 대여'
            END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE A.START_DATE BETWEEN TO_DATE('2022-09-01','YYYY-MM-DD') AND TO_DATE('2022-09-30','YYYY-MM-DD')
ORDER BY 1 DESC



