-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM (SELECT * FROM ANIMAL_INS ORDER BY DATETIME) A
WHERE NOT EXISTS (SELECT 1
                 FROM ANIMAL_OUTS B 
                 WHERE B.ANIMAL_ID = A.ANIMAL_ID)
                 AND ROWNUM <=3
ORDER BY A.DATETIME ASC
