-- 코드를 입력하세요
SELECT A.PRODUCT_ID,B.PRODUCT_NAME, SUM(A.AMOUNT * B.PRICE) AS TOTAL_SALES 
FROM FOOD_ORDER A JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE A.PRODUCE_DATE BETWEEN TO_DATE('2022-05-01','YYYY-MM-DD') AND TO_DATE('2022-05-31','YYYY-MM-DD')
GROUP BY A.PRODUCT_ID, B.PRODUCT_NAME
ORDER BY 3 DESC, 1