-- 코드를 입력하세요
SELECT A.MEMBER_NAME,B.REVIEW_TEXT,TO_CHAR(B.REVIEW_DATE,'YYYY-MM-DD')
FROM MEMBER_PROFILE A JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = (SELECT MEMBER_ID
                      FROM (SELECT MEMBER_ID,COUNT(MEMBER_ID) AS CNT
                            FROM REST_REVIEW
                           GROUP BY MEMBER_ID) I
                      ORDER BY I.CNT DESC
                     FETCH FIRST 1 ROWS ONLY)
ORDER BY 3,2