SELECT ID,FISH_NAME,LENGTH
FROM FISH_INFO 
JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE LENGTH IN (SELECT MAX(LENGTH)
                FROM FISH_INFO
                WHERE FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
               GROUP BY FISH_TYPE)
ORDER BY ID